### ISSUE TITLE
Is the "query_api.py" file missing

### ISSUE THREAD

**Issue by xuemenglong** [microsoft/RecAI#57]
RecLM-emb/shell/test_data_pipeline.sh, line 56, shows python preprocess/gpt_api/query_api. py, but there is no query_api. py file in the RecLM-emb/preprocess/gpt_api/ directory, only the api. py file. May I ask if the file is missing?

**Comment by Micheallei** [comment]
Thanks for your feedback.
The actual file used here is api.py. We will correct the script.
