### ISSUE TITLE
Question: If I successfully run these six modules, can they be immediately combined into a usable recommendation system?

### ISSUE THREAD

**Issue by zzhdbw** [microsoft/RecAI#61]
As shown in the question: If I successfully run these six modules, can they be immediately combined into a usable recommendation system?

We look forward to your reply.

**Comment by Leavingseason** [comment]
Each of the six modules corresponds to an individual pillar, you don't even need to run all of them in order to incorporate it into your systems. Just pick up the useful one or more modules.

**Comment by zzhdbw** [comment]
okok，Thank you for your reply！
