### ISSUE TITLE
RecLM-emb question

### ISSUE THREAD

**Issue by zzhdbw** [microsoft/RecAI#62]
bash shell/data_pipeline.sh
bash shell/test_data_pipeline.sh

The above script will consume a lot of cost to call OpenAI. Can you provide the file generated after executing the script? Looking forward to your reply.

**Comment by Leavingseason** [comment]
I also wish we can release the OAI response data. However, before releasing data we need to go through a long responsibility review process which will cost us a lot of time. So, we suggest users to run the script by themselves. Alternatively, you can also use Llama 3 70B or 3.1 405B model to replace OpenAI APIs in the script.

**Comment by zzhdbw** [comment]
Okay, thank you for your reply！
