### ISSUE TITLE
URL RecLLaMA Checkpoint Not Working

### ISSUE THREAD

**Issue by tuanlda78202** [microsoft/RecAI#63]
The checkpoint model [RecLLaMA](https://github.com/microsoft/RecAI/blob/main/InteRecAgent/README.md) URL referenced in the README is not working, I cannot access it.

**Comment by Leavingseason** [comment]
We remove RecLLaMA part and the README file from the project, but forgot to update some other section in the main README file. Sorry about the confusion and I will update this section shortly. This part is for hosting any opensource models (like Llama) in the same way as having OpenAI API in InteRecAgent.

**Comment by Leavingseason** [comment]
Yes, according to our experience, small LLMs such as 7B models cannot do tool invoke well.  Our RecLlama is finetuned with GPT-4's tool usage tragetories and its tool invoking got much better. 
If without finetuning, I think you can try LLaMA 3.1's bigger version model.

**Comment by tuanlda78202** [comment]
Could you please provide me with the link to the RecLLaMa checkpoint for testing purposes? I am a student, and this is strictly for educational research.

I would greatly appreciate your assistance, as it is crucial for my project. If possible, could you share it with me via my [email](mailto:tuanleducanh78202@gmail.com)? Thank you very much! @Leavingseason

**Comment by tuanlda78202** [comment]
I tried `gemma2-9b-it`, and it works! Thanks for the recommendation
