### ISSUE TITLE
Request for Details on SFT LLMs for Tool Execution in InteRecAgent

### ISSUE THREAD

**Issue by tuanlda78202** [microsoft/RecAI#67]
First and foremost, thank you for the excellent work on the InteRecAgent. I truly appreciate the effort and expertise that went into it.

I have thoroughly read the "InteRecAgent" paper and am excited to use your pipeline for my project. However, the paper does not provide detailed information on how you fine-tuned RecLlama, except for the overall architecture diagram. 
![image](https://github.com/user-attachments/assets/c269c193-03b4-44c0-8dfb-12d72dee090e)

Could you please provide me with the following:

1. **Instruction Following Template for SFT**:
   - Could you share the format of the instruction-following template for SFT, including a few sample workflows? This would greatly help me understand the process.

2. **Details on Data Extraction for SFT**:
   - How did you extract information to create synthetic data for SFT when the simulator chat interacted with the agent? Specific details on this process would be highly beneficial.

3. **Multilingual Reasoning Capabilities**:
   - I plan to use your pipeline for the Vietnamese language. In your experience, will the current multilingual reasoning capabilities, combined with your pipeline, work effectively for this language?

Thank you for your time and consideration. I look forward to your response.@Leavingseason

**Comment by XuHwang** [comment]
Hey, thanks for your interest and questions. Here are the answers to your questions.

1. I understand what you want is the system prompt in our SFT data. We kept the prompt consistent with what is used for GPT-4. The detailed prompt can be found [here](https://github.com/microsoft/RecAI/blob/main/InteRecAgent/llm4crs/prompt/system.py).
2. We collect all the inputs and outputs of the API calling in the simulation stage, forming one part of the SFT data.
3. Although I have not tried other languages, I think applying our pipeline to your language is completely okay. What you need is a multilingual LLM (such as GPT-4) and then tune the prompt into your language. If you need a local LLM, you can follow our method to collect SFT data in the simulation stage or synthesize conversational data with GPT-4.

I hope those explanations can address your issues.

**Comment by tuanlda78202** [comment]
Thank you very much for the prompt reply!
