### ISSUE TITLE
questions about the inference procedure of sequential recommendation

### ISSUE THREAD

**Issue by tiebreaker4869** [microsoft/RecAI#72]
in the templates.py file under sft folder there are 2 templates for sequential recommendations, one has candidates in input while the other does not, i wonder which one is used during the evaluation of sequential recommendation tasks? or both are used in some way? Thank you!

**Comment by Luuuk12321** [comment]
@tiebreaker4869 
We use 2 templates(with/without candidates) while training. Refer to [Train_task_group_mapping["SFTSeqRec"]](https://github.com/microsoft/RecAI/blob/2fe6d63b9766e1aae34f7ba5576f73764dd19013/RecLM-gen/sft/dataset.py#L525).
In model evaluation, we separate them into 2 classes of instruction. [Test_task_group_mapping["SFTTestSeqRec"]](https://github.com/microsoft/RecAI/blob/2fe6d63b9766e1aae34f7ba5576f73764dd19013/RecLM-gen/sft/dataset.py#L548) without candidates, [Test_task_group_mapping["SFTTestSeqRanking"]](https://github.com/microsoft/RecAI/blob/2fe6d63b9766e1aae34f7ba5576f73764dd19013/RecLM-gen/sft/dataset.py#L549) with candidates.
We use the one without candidates during the evaluation of sequential recommendation tasks.

**Comment by tiebreaker4869** [comment]
helpful answers.  thanks for ur explanation!
