### ISSUE TITLE
InteRecAgent running error

### ISSUE THREAD

**Issue by user407769581** [microsoft/RecAI#74]
$ DOMAIN=game python app.py --engine gpt-4
C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio_client\documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
Columns in item corups: Index(['id', 'title', 'tags', 'release_date', 'price', 'description',
       'visited_num'],
      dtype='object').
C:\Users\27121\Desktop\RecAI-main\InteRecAgent\llm4crs\demo\base.py:54: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  HuggingFaceEmbeddings(),
C:\Users\27121\Desktop\RecAI-main\InteRecAgent\llm4crs\demo\base.py:54: LangChainDeprecationWarning: Default values for HuggingFaceEmbeddings.model_name were deprecated in LangChain 0.2.16 and will be removed in 0.4.0. Explicitly pass a model_name to the HuggingFaceEmbeddings constructor instead.
  HuggingFaceEmbeddings(),
[2024-10-22 10:35:52 DEBUG] Mode changed to accuracy.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.40.1, however version 4.44.1 is available, please upgrade.
--------
[2024-10-22 10:36:00 DEBUG] 
Processing run_text, Input text:
Current state: [[None, "Hello, I'm a conversational game recommendation assistant. I'm here to help you discover your interested games."], ['', None]]
Current Memory:

[2024-10-22 10:36:00 DEBUG] Here is the exception: module 'openai' has no attribute 'api_base'
![Image](https://github.com/user-attachments/assets/0ee72783-e21d-4894-99f2-e18b11e3636a)

**Comment by user407769581** [comment]
If I update Gradio, then $ DOMAIN=game python app.py --engine gpt-4
Traceback (most recent call last):
  File "C:\Users\27121\Desktop\RecAI-main\InteRecAgent\app.py", line 7, in <module>
    import gradio as gr
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    import PIL.Image
  File "C:\Users\27121\anaconda3\envs\interecagent\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by XuHwang** [comment]
It seems to be the version conflict of `openai`, can you provide the your version of `openai`?

**Comment by user407769581** [comment]
Thank you very much for your reply. However, when I reinstalled the dependencies, a new error occurred during startup
![Image](https://github.com/user-attachments/assets/64b45198-3e3e-4d58-993d-be6abe5e7d23)

**Comment by user407769581** [comment]
Here is my dependent version
# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
accelerate                1.0.1                    pypi_0    pypi
aiofiles                  23.2.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.4.1              pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
anyio                     3.7.1                    pypi_0    pypi
aom                       3.9.1                he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0             pyh71513ae_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backoff                   2.2.1              pyhd8ed1ab_0    conda-forge
bcrypt                    4.2.0            py39h92a245a_1    conda-forge
brotli                    1.1.0                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotli-bin                1.1.0                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotli-python             1.1.0            py39ha51f57c_2    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.8.30            h56e8100_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                5.5.0                    pypi_0    pypi
cairo                     1.18.0               h32b962e_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1           py39ha55e580_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
chroma-hnswlib            0.7.6                    pypi_0    pypi
chromadb                  0.4.7                    pypi_0    pypi
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cloudpickle               3.1.0                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1             pyhd8ed1ab_3    conda-forge
contourpy                 1.3.0            py39h2b77a98_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cryptography              43.0.3                   pypi_0    pypi
cuda-version              11.8                 h70ddcb2_3    conda-forge
cudatoolkit               11.8.0              h09e9e62_13    conda-forge
cudnn                     9.3.0.75             h4ba422f_0    conda-forge
cvxpy                     1.3.1                    pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dask                      2024.8.0                 pypi_0    pypi
dask-expr                 1.1.10                   pypi_0    pypi
dataclasses-json          0.6.7                    pypi_0    pypi
dav1d                     1.2.1                hcfcfb64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
debugpy                   1.8.7                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
dlfcn-win32               1.4.1                h63175ca_0    conda-forge
dnspython                 2.7.0              pyhff2d567_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
ecos                      2.0.14                   pypi_0    pypi
email-validator           2.2.0              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
email_validator           2.2.0                hd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
expat                     2.6.3                he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
faiss-cpu                 1.7.4                    pypi_0    pypi
fastapi                   0.115.4            pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fastapi-cli               0.0.5              pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
feather-format            0.4.1                    pypi_0    pypi
ffmpeg                    7.1.0           gpl_hb26d62f_702    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
font-ttf-inconsolata      2.000                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
font-ttf-source-code-pro  2.030                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
font-ttf-ubuntu           0.83                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
fontconfig                2.14.2               hbde0cde_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fonts-conda-ecosystem     1                             0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fonts-conda-forge         1                             0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fonttools                 4.54.1           py39hf73967f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
freetype                  2.12.1               hdaf720e_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fribidi                   1.0.10               h8d14728_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2024.10.0          pyhff2d567_0    conda-forge
gdk-pixbuf                2.42.12              hed59a49_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gptcache                  0.1.44                   pypi_0    pypi
gradio                    3.40.1                   pypi_0    pypi
gradio-client             1.3.0                    pypi_0    pypi
graphite2                 1.3.13            h63175ca_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
greenlet                  3.1.1                    pypi_0    pypi
grpcio                    1.67.0                   pypi_0    pypi
guidance                  0.0.64                   pypi_0    pypi
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
harfbuzz                  9.0.0                h2bedf89_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.6              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
httptools                 0.6.1            py39ha55e580_1    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
huggingface_hub           0.26.1             pyh0610db2_0    conda-forge
humanfriendly             10.0             py39hcbf5309_5    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
importlib-resources       6.4.5              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
joblib                    1.4.2                    pypi_0    pypi
jsonpatch                 1.33                     pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
kiwisolver                1.4.7            py39h2b77a98_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
langchain                 0.0.312                  pypi_0    pypi
langsmith                 0.0.92                   pypi_0    pypi
lcms2                     2.16                 h67d730c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lerc                      4.0.0                h63175ca_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libabseil                 20240116.2      cxx17_he0c23c2_1    conda-forge
libblas                   3.9.0              25_win64_mkl    conda-forge
libbrotlicommon           1.1.0                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libbrotlidec              1.1.0                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libbrotlienc              1.1.0                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0              25_win64_mkl    conda-forge
libcurl                   8.10.1               h1ee3ff0_0    conda-forge
libdeflate                1.22                 h2466b09_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libexpat                  2.6.3                he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.82.2               h7025463_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
liblapack                 3.9.0              25_win64_mkl    conda-forge
libopus                   1.3.1                h8ffe710_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.44               h3ca93ac_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libprotobuf               4.25.3               h47a098d_1    conda-forge
libpulsar                 3.5.1                h13e8e67_2    conda-forge
librsvg                   2.58.4               h33bc1f6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.47.0               h2466b09_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.7.0                hfc51747_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.4.0                hcfcfb64_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcb                    1.16                 h013a479_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
libzlib-wapi              1.3.1                h2466b09_2    conda-forge
linkify-it-py             2.0.3                    pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loguru                    0.7.0                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
m2w64-gcc-libs            5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
m2w64-gcc-libs-core       5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
m2w64-gmp                 6.1.0                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
markdown                  3.7                      pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.5            py39ha55e580_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
marshmallow               3.23.0                   pypi_0    pypi
matplotlib-base           3.9.2            py39h5376392_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl                       2024.2.2            h66d3029_14    conda-forge
monotonic                 1.5                pyhd8ed1ab_1    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msal                      1.31.0                   pypi_0    pypi
msys2-conda-epoch         20160418                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
multidict                 6.1.0                    pypi_0    pypi
munkres                   1.0.7                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
mypy-extensions           1.0.0                    pypi_0    pypi
narwhals                  1.10.0                   pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
nltk                      3.9.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4           py39hddb5d58_0    conda-forge
onnxruntime               1.19.2                   pypi_0    pypi
openai                    0.27.9                   pypi_0    pypi
openh264                  2.4.1                h63175ca_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openjpeg                  2.5.2                h3d672ee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   3.3.2                h2466b09_0    conda-forge
orjson                    3.10.10          py39he61d37a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
osqp                      0.6.7.post3              pypi_0    pypi
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3                    pypi_0    pypi
pandasql                  0.7.3                    pypi_0    pypi
pango                     1.54.0               hbb871f6_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
partd                     1.4.2                    pypi_0    pypi
pcre2                     10.44                h3d7b363_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pillow                    10.4.0           py39hfa8c767_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       24.2               pyh8b19718_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pixman                    0.43.4               h63175ca_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
platformdirs              4.3.6                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
posthog                   3.6.5              pyhd8ed1ab_0    conda-forge
propcache                 0.2.0                    pypi_0    pypi
protobuf                  4.25.3           py39h434d6e0_1    conda-forge
psutil                    6.1.0                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pthreads-win32            2.9.1                h2466b09_4    conda-forge
pulsar-client             3.5.0            py39ha51f57c_1    conda-forge
pyarrow                   17.0.0                   pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.9.2              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pydantic-core             2.23.4           py39h92a245a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pydub                     0.25.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pygtrie                   2.5.0                    pypi_0    pypi
pyjwt                     2.9.0                    pypi_0    pypi
pyparsing                 3.2.0              pyhd8ed1ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pypika                    0.48.9             pyhd8ed1ab_0    conda-forge
pyreadline3               3.5.4            py39hcbf5309_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytest                    8.3.3                    pypi_0    pypi
python                    3.9.20          hfaddaf0_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1              pyhd8ed1ab_0    conda-forge
python-flatbuffers        24.3.25            pyh59ac667_0    conda-forge
python-multipart          0.0.12                   pypi_0    pypi
python-tzdata             2024.2             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python_abi                3.9                      5_cp39    conda-forge
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2            py39ha55e580_1    conda-forge
qdldl                     0.1.7.post4              pypi_0    pypi
qhull                     2020.2               hc790b64_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
rapidfuzz                 3.2.0                    pypi_0    pypi
referencing               0.35.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
regex                     2024.9.11                pypi_0    pypi
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.9.3             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
rpds-py                   0.20.0           py39h92a245a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ruff                      0.7.1            py39he05c28a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
safetensors               0.4.5                    pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
scs                       3.2.7                    pypi_0    pypi
semantic_version          2.10.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
sentry-sdk                2.17.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                75.1.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.1                    pypi_0    pypi
snappy                    1.2.1                h23299a8_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.46                   pypi_0    pypi
sqlite                    3.47.0               h2466b09_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sqlparse                  0.4.2                    pypi_0    pypi
starlette                 0.41.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
svt-av1                   2.2.1                he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
swifter                   1.4.0                    pypi_0    pypi
sympy                     1.13.3             pyh04b8f61_4    conda-forge
tbb                       2021.13.0            hc790b64_0    conda-forge
tenacity                  8.5.0                    pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tiktoken                  0.4.0                    pypi_0    pypi
tk                        8.6.13               h5226925_1    conda-forge
tokenizers                0.20.1           py39hb5dfeee_0    conda-forge
tomli                     2.0.2                    pypi_0    pypi
tomlkit                   0.12.0             pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
toolz                     1.0.0                    pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
transformers              4.46.0                   pypi_0    pypi
typer                     0.12.5             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
typer-slim                0.12.5             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
typer-slim-standard       0.12.5               hd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing-inspect            0.9.0                    pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024b                hc8b5060_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
uc-micro-py               1.0.3                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
unicodedata2              15.1.0           py39ha55e580_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
unirec                    0.0.1a4                  pypi_0    pypi
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
uvicorn                   0.32.0           py39hcbf5309_0    conda-forge
uvicorn-standard          0.32.0               hcbf5309_0    conda-forge
vc                        14.3                h8a93ad2_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc14_runtime              14.40.33810         hcc2c482_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.40.33810         h3bf8584_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wandb                     0.18.5                   pypi_0    pypi
watchfiles                0.24.0           py39h92a245a_1    conda-forge
websockets                11.0.3           py39ha55989b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
werkzeug                  3.0.5                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
win32-setctime            1.1.0                    pypi_0    pypi
win_inet_pton             1.1.0              pyh7428d3b_7    conda-forge
x264                      1!164.3095           h8ffe710_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
x265                      3.5                  h2d74725_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxau               1.0.11               hcd874cb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yarl                      1.16.0                   pypi_0    pypi
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zstandard                 0.23.0           py39h9bf74da_1    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

**Comment by XuHwang** [comment]
This issue seems to arise from a breaking change in huggingface_hub version 0.26.0, where the cached_download() function has been fully removed. Downgrading to an earlier version of huggingface_hub should resolve this problem.

More details: https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0
