### ISSUE TITLE
[RecExplainer] Error in Dataset Preparation

### ISSUE THREAD

**Issue by waterluy** [microsoft/RecAI#79]
Thank you for your excellent work!

When I run the command ```bash shell/preprocess_recmodel.sh```, I encounter the following error. Could you please guide me on how to resolve it, how can I obtain the file ```unirec_raw_data/amazon_video_games_v3/train.tsv```? I would appreciate your response.

```FileNotFoundError: [Errno 2] No such file or directory: '~/RecAI/RecExplainer/data/unirec_raw_data/amazon_video_games_v3/train.tsv'```

**Comment by Micheallei** [comment]
Thank you for your interest in our work!

To resolve the issue, please create the following folder:
~/RecAI/RecExplainer/data/unirec_raw_data/amazon_video_games_v3

Once the folder is created, the script should run without issues.
